version: '3.4'

x-common-variables: &common-variables
 CELERY_BROKER_URL: redis://redis:6379
 CELERY_RESULT_BACKEND: redis://redis:6379
 RESTRICTED_MODE: 0
 FLASK_APP: manage.py

services:
 hse-api-web:
  build:
   context: .
   dockerfile: hseling_api_autotutor/Dockerfile
  ports:
   - "5000:80"
  volumes:
   - ./hseling_api_autotutor/hseling_api_autotutor:/app/hseling_api_autotutor
  links:
   - redis
  environment: *common-variables

 redis:
  image: redis:latest

 # Development related
 db:
  env_file: hseling_web_autotutor/environment.env
  build:
   context: ./hseling_web_autotutor/
   dockerfile: ./docker/db/Dockerfile
   args:
    # These values should be in sync with environment.env
    # for development. If you change them, you'll 
    # need to rebuild the container
    - POSTGRES_DB=seleniumserver
    - POSTGRES_USER=userbd
    - POSTGRES_PASSWORD=Qqqq2222
    - POSTGRES_PORT=5432
    # Remember to keep this consistent
    - django_secret_key=hhz1t!=p^!%jrnkehfjj94678&eoi_bgojcb=o&ebc29d4^e%g

 log:
  env_file: hseling_web_autotutor/environment.env
  build:
   context: ./hseling_web_autotutor/
   dockerfile: ./docker/log/Dockerfile

 build-deps:
  env_file: hseling_web_autotutor/environment.env
  build:
   context: ./hseling_web_autotutor/
   dockerfile: ./docker/deps/Dockerfile
  volumes:
   - ./hseling_web_autotutor/vendor:/opt/ext_vendor
  command: /opt/copy_deps.sh

 dev-server:
  env_file: hseling_web_autotutor/environment.env
  environment:
   - CONSOLE_LOGS=1
  build: 
   context: ./hseling_web_autotutor/
   args:
    # Remember to keep this consistent
    - django_secret_key=hhz1t!=p^!%jrnkehfjj94678&eoi_bgojcb=o&ebc29d4^e%g
  command: ./start_dev_server.sh
  ports:
   - "8000:80"
  volumes:
   - ./hseling_web_autotutor/src:/opt/code
  depends_on:
   - db
   - log
   - hse-api-web

volumes:
  data:
