# Generated by Django 2.2.4 on 2020-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unsv_counter',
            field=models.IntegerField(default=0),
        ),
    ]
